// <auto-generated />
namespace _036_MoviesMvcWissen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class vwUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vwUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202002181801572_vwUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
